trigger:
- master
 
pool:
  name: iacmanagedpool
  vmImage: 'windows-latest'

steps:

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: ‘Install Terraform 2.0.0’
  inputs:
    terraformVersion: 2.0.0

- task: TerraformTaskV4@4
  displayName: Terraform- Init' 
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'iacterraforminfradeployment'
    backendAzureRmResourceGroupName: 'example-resource-group'
    backendAzureRmStorageAccountName: 'iacqaautomationtstate'
    backendAzureRmContainerName: 'tstate'
    backendAzureRmKey: '0seHMQKA6FPH3uH4HhHXeF8x7XyIYTU8uygyV9uS8KSPIA7UFVKPoGPktNGV0KfYvLHS7tgcnrUt+AStngpq1w=='

- task: TerraformTaskV4@4
  displayName: Terraform- Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'iacterraforminfradeployment'

- task: TerraformTaskV4@4
  displayName: Terraform- Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTaskV4@4
  displayName: Terraform- Apply Infra provisioning'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'iacterraforminfradeployment'
